
python test_robust.py \
	--dataset_in ${1} \
	--n_classes ${2} \
	--num_samples ${3} \
	--model ${4} \
	--conv_expand ${5} \
	--fc_expand ${6} \
	--depth ${7} \
	--width ${8} \
	--batch_size 128 \
	--test_batch_size 128 \
	--lr_schedule ${9} \
	--learning_rate ${10} \
	--attack ${11} \
	--epsilon ${12} \
	--attack_iter ${13} \
	--gamma ${14} \
	--clip_min 0.0 \
	--clip_max 1.0 \
	--eps_schedule ${15} \
	--num_restarts ${16} \
	--last_epoch 0 \
	--checkpoint_path trained_models \
	--marking_strat ${17} \
	--matching_path matchings \
	--degree_path graph_data/degree_results \
	--norm ${18} \
	--drop_thresh ${19} \
	--curriculum ${20} \
	--loss_fn ${21} \
	--new_attack ${22} \
	--new_epsilon ${23} \
	--new_attack_iter ${24} \
	--new_gamma ${25} \
	--new_num_restarts ${26} \
	--new_marking_strat ${27} \
	--num_of_trials ${28} \
	${29} `#is_adv` \
	${30} `#targeted` \
	${31} `#rand_init` \
	${32} `#is_dropping` \
	${33} `#is_viz` \
	${34} `#save_test` \
	${35} `#track_hard` \
	${36} `#new_rand_init` \