
python test_robust.py \
	--dataset_in ${1} \
	--n_classes ${2} \
	--num_samples ${3} \
	--model ${4} \
	--conv_expand ${5} \
	--fc_expand ${6} \
	--depth ${7} \
	--width ${8} \
	--batch_size 128 \
	--test_batch_size 128 \
	--lr_schedule ${9} \
	--attack ${10} \
	--epsilon ${11} \
	--attack_iter ${12} \
	--gamma ${13} \
	--clip_min 0.0 \
	--clip_max 1.0 \
	--eps_schedule ${14} \
	--num_restarts ${15} \
	--last_epoch 0 \
	--checkpoint_path trained_models \
	--marking_strat ${16} \
	--matching_path matchings \
	--degree_path graph_data/degree_results \
	--norm ${17} \
	--drop_thresh ${18} \
	--curriculum ${19} \
	--loss_fn ${20} \
	--new_attack ${21} \
	--new_epsilon ${22} \
	--new_attack_iter ${23} \
	--new_gamma ${24} \
	--new_num_restarts ${25} \
	--new_marking_strat ${26} \
	--num_of_trials ${27} \
	${28} `#is_adv` \
	${29} `#targeted` \
	${30} `#rand_init` \
	${31} `#is_dropping` \
	${32} `#is_viz` \
	${33} `#save_test` \
	${34} `#track_hard` \
	${35} `#new_rand_init` \