# generic 
arch: "resnet18" # prefer densenet/WideResNet (ref: bag of tricks adv. training)
channels: 1

# dataset
dataset: "mnist_3_7"
data_dir: "./data/"
mode: "base"
num_classes: 2
size: 28
normalize: False
workers: 4

# optimization
epochs: 20
batch_size: 128
lr: 0.01
weight_decay: 0.0002
momentum: 0.9

# adversarial examples
epsilon: 3.0
num_steps: 40
step_size: 0.5
clip_min: 0.
clip_max: 1.
distance: "l2"
beta: 6.0
